provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  orchestrator:
    lang: dockerfile
    handler: ./functions/orchestrator
    image: fave-orchestrator:dev
    environment:
      GATEWAY_URL: http://gateway.openfaas:8080
      ARTIFACT_BUCKET: fave-artifacts
      ORCHESTRATOR_DRY_RUN: "true"
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-ffmpeg-0:
    lang: dockerfile
    handler: ./functions/stage-ffmpeg-0
    image: fave-stage-ffmpeg-0:dev
    environment:
      STAGE_NAME: stage-ffmpeg-0
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-librosa:
    lang: dockerfile
    handler: ./functions/stage-librosa
    image: fave-stage-librosa:dev
    environment:
      STAGE_NAME: stage-librosa
    secrets:
      - artifact-access-key
      - artifact-secret-key
