provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  orchestrator:
    lang: dockerfile
    handler: ./functions/orchestrator
    image: fave-orchestrator:dev
    environment:
      GATEWAY_URL: http://gateway.openfaas:8080
      ARTIFACT_BUCKET: fave-artifacts
      ORCHESTRATOR_DRY_RUN: "false"
      ENABLE_OBJECT_DETECTOR: "true"
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-ffmpeg-0:
    lang: dockerfile
    handler: ./functions/stage-ffmpeg-0
    image: fave-stage-ffmpeg-0:dev
    environment:
      STAGE_NAME: stage-ffmpeg-0
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-librosa:
    lang: dockerfile
    handler: ./functions/stage-librosa
    image: fave-stage-librosa:dev
    environment:
      STAGE_NAME: stage-librosa
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-ffmpeg-1:
    lang: dockerfile
    handler: ./functions/stage-ffmpeg-1
    image: fave-stage-ffmpeg-1:dev
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-ffmpeg-2:
    lang: dockerfile
    handler: ./functions/stage-ffmpeg-2
    image: fave-stage-ffmpeg-2:dev
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-deepspeech:
    lang: dockerfile
    handler: ./functions/stage-deepspeech
    image: fave-stage-deepspeech:dev
    environment:
      DEEPSPEECH_MODEL: /opt/models/deepspeech-0.9.3-models.pbmm
      DEEPSPEECH_SCORER: /opt/models/deepspeech-0.9.3-models.scorer
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-ffmpeg-3:
    lang: dockerfile
    handler: ./functions/stage-ffmpeg-3
    image: fave-stage-ffmpeg-3:dev
    environment:
      FRAME_VF: "fps=12/60"
    secrets:
      - artifact-access-key
      - artifact-secret-key

  stage-object-detector:
    lang: dockerfile
    handler: ./functions/stage-object-detector
    image: fave-stage-object-detector:dev
    environment:
      MODEL_PATH: /opt/models/model.onnx
      LABEL_PATH: /opt/models/coco.names
    secrets:
      - artifact-access-key
      - artifact-secret-key
